TARGETED_HOUR_BIRTHDAY_REMINDER = (8, 0)  # (9, 0)
DEFAULT_NAME_KEY = "nom"
DEFAULT_FIRSTNAME_KEY = "prenom"
DEFAULT_GENERAL_CHANNEL = "bla-bla-bla"
DEFAULT_TIMEZONE = "Europe/Paris"
DEFAULT_CELEBRITE_KEY = "CELEBRITE"
