TARGETED_HOUR_BIRTHDAY_REMINDER = (14, 9)  # (9, 0)
DEFAULT_NAME_KEY = "nom"
DEFAULT_FIRSTNAME_KEY = "prenom"
DEFAULT_GENERAL_CHANNEL = "général"
DEFAULT_TIMEZONE = "Europe/Paris"
DEFAULT_CELEBRITE_KEY = "CELEBRITE"
