TARGETED_HOUR_BIRTHDAY_REMINDER = (9, 0)
TARGETED_HOUR_RESET_TOPIC = (0, 1)
DEFAULT_NAME_KEY = "nom"
DEFAULT_FIRSTNAME_KEY = "prenom"
DEFAULT_GENERAL_CHANNEL = "bla-bla-bla"
DEFAULT_TIMEZONE = "Europe/Paris"
DEFAULT_CELEBRITE_KEY = "CELEBRITE"
DEFAULT_TOPIC = "Salon pour parler de tout, de rien et des anniversaires."
